apiVersion: v1
kind: Namespace
metadata:
  name: rocketmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-namesrv
  namespace: rocketmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-namesrv
  template:
    metadata:
      labels:
        app: rocketmq-namesrv
    spec:
      containers:
      - name: namesrv
        image: apache/rocketmq:5.0.1
        command: ["sh", "mqnamesrv"]
        ports:
        - containerPort: 9876
        env:
        - name: JAVA_OPT_EXT
          value: "-server -Xms512m -Xmx512m"
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-namesrv
  namespace: rocketmq
spec:
  selector:
    app: rocketmq-namesrv
  ports:
  - port: 9876
    targetPort: 9876
  type: ClusterIP